version: "3.9"
services:
  gateway:
    build: gateway
    container_name: shareit-gateway
    environment:
      - SHAREIT_SERVER_URL=server:8081
    networks:
      - gateway-network
      - server_network
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
  server:
    build: server
    container_name: shareit-server
    networks:
      - server_network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
  db:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - server_network

volumes:
  db:

networks:
  server_network:
    driver: bridge
  gateway-network:
    driver: bridge