spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    username: shareit
    password: shareit
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: 'true'
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        transaction:
          nodeValue: INFO
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO

---
spring:
  datasource:
    url: jdbc:h2:mem:shareit
    username: test
    password: test
    driverClassName: org.h2.Driver
  config:
    activate:
      on-profile: ci,test